.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Shell.Xu <shell909090@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OTPKNOCK SECTION "September 27, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
otpknock \- port knocking by otp auth
.SH SYNOPSIS
.B otpknock
.RI [ -config
config_file]
.SH DESCRIPTION
Port knocking daemon auth client by otp (google authentication).
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-\-config
set config file.
.SH SEE ALSO
.BR optknock.ini
